package export

import (
	"fmt"
	"strings"
	"time"
)

// ExportPayload represents the data structure to be exported as PDF, Text, or Markdown.
type ExportPayload struct {
	Title          string
	Summary        string
	KeyPoints      []string
	Explanation    string
	TranscriptText string
	Language       string
	DetailLevel    string
	TargetAudience string
	SourceType     string // "Speech-to-Text", "Document", "Audio"
	CreatedAt      time.Time
}

// GenerateText creates formatted plain text output for speech/document summaries.
func GenerateText(p ExportPayload) []byte {
	var sb strings.Builder

	created := p.CreatedAt
	if created.IsZero() {
		created = time.Now()
	}

	sb.WriteString("================================================================================\n")
	sb.WriteString(" EQUILILEARN - AI LEARNING SUMMARY\n")
	sb.WriteString("================================================================================\n\n")

	sb.WriteString(fmt.Sprintf("TITLE:           %s\n", p.Title))
	sb.WriteString(fmt.Sprintf("SOURCE:          %s\n", p.SourceType))
	sb.WriteString(fmt.Sprintf("DATE:            %s\n", created.Format("02 Jan 2006, 15:04 MST")))
	if p.Language != "" {
		sb.WriteString(fmt.Sprintf("LANGUAGE:        %s\n", strings.ToUpper(p.Language)))
	}
	if p.DetailLevel != "" {
		sb.WriteString(fmt.Sprintf("DETAIL LEVEL:    %s\n", strings.Title(p.DetailLevel)))
	}
	if p.TargetAudience != "" {
		sb.WriteString(fmt.Sprintf("TARGET AUDIENCE: %s\n", strings.Title(p.TargetAudience)))
	}
	sb.WriteString("\n--------------------------------------------------------------------------------\n")
	sb.WriteString(" [EXECUTIVE SUMMARY]\n")
	sb.WriteString("--------------------------------------------------------------------------------\n\n")
	sb.WriteString(p.Summary)
	sb.WriteString("\n\n")

	if len(p.KeyPoints) > 0 {
		sb.WriteString("--------------------------------------------------------------------------------\n")
		sb.WriteString(" [KEY TAKEAWAYS]\n")
		sb.WriteString("--------------------------------------------------------------------------------\n\n")
		for i, kp := range p.KeyPoints {
			sb.WriteString(fmt.Sprintf("  %d. %s\n", i+1, kp))
		}
		sb.WriteString("\n")
	}

	if p.Explanation != "" {
		sb.WriteString("--------------------------------------------------------------------------------\n")
		sb.WriteString(" [IN-DEPTH CONCEPTUAL EXPLANATION]\n")
		sb.WriteString("--------------------------------------------------------------------------------\n\n")
		sb.WriteString(p.Explanation)
		sb.WriteString("\n\n")
	}

	if p.TranscriptText != "" {
		sb.WriteString("--------------------------------------------------------------------------------\n")
		sb.WriteString(" [ORIGINAL SPEECH TRANSCRIPT]\n")
		sb.WriteString("--------------------------------------------------------------------------------\n\n")
		sb.WriteString(p.TranscriptText)
		sb.WriteString("\n\n")
	}

	sb.WriteString("================================================================================\n")
	sb.WriteString(" Generated by EquiliLearn - Empowering Accessible Learning for Everyone\n")
	sb.WriteString("================================================================================\n")

	return []byte(sb.String())
}

// GenerateMarkdown creates structured markdown output for speech/document summaries.
func GenerateMarkdown(p ExportPayload) []byte {
	var sb strings.Builder

	created := p.CreatedAt
	if created.IsZero() {
		created = time.Now()
	}

	sb.WriteString(fmt.Sprintf("# %s\n\n", p.Title))
	sb.WriteString(fmt.Sprintf("> **Source:** %s | **Date:** %s | **Language:** %s | **Detail:** %s\n\n",
		p.SourceType,
		created.Format("02 Jan 2006"),
		strings.ToUpper(p.Language),
		strings.Title(p.DetailLevel),
	))

	sb.WriteString("## 📝 Executive Summary\n\n")
	sb.WriteString(p.Summary)
	sb.WriteString("\n\n")

	if len(p.KeyPoints) > 0 {
		sb.WriteString("## 💡 Key Takeaways\n\n")
		for _, kp := range p.KeyPoints {
			sb.WriteString(fmt.Sprintf("- %s\n", kp))
		}
		sb.WriteString("\n")
	}

	if p.Explanation != "" {
		sb.WriteString("## 🧠 In-Depth Conceptual Explanation\n\n")
		sb.WriteString(p.Explanation)
		sb.WriteString("\n\n")
	}

	if p.TranscriptText != "" {
		sb.WriteString("## 🎙️ Original Speech Transcript\n\n")
		sb.WriteString("```text\n")
		sb.WriteString(p.TranscriptText)
		sb.WriteString("\n```\n\n")
	}

	sb.WriteString("---\n*Generated by EquiliLearn AI Assistant*\n")

	return []byte(sb.String())
}
